"""Biot-Savart forward models and validation references."""

from __future__ import annotations

from collections.abc import Sequence

import numpy as np

from .geometry import Coil

MU0 = 4e-7 * np.pi


def _basis_from_normal(normal: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    n = normal / np.linalg.norm(normal)
    helper = np.array([1.0, 0.0, 0.0])
    if abs(np.dot(n, helper)) > 0.9:
        helper = np.array([0.0, 1.0, 0.0])
    u = np.cross(n, helper)
    u /= np.linalg.norm(u)
    v = np.cross(n, u)
    return u, v


def loop_segments(coil: Coil) -> tuple[np.ndarray, np.ndarray]:
    """Return midpoint positions and directed segment vectors for a coil."""
    u, v = _basis_from_normal(coil.unit_normal)
    theta = np.linspace(0.0, 2.0 * np.pi, coil.segments + 1)
    vertices = (
        np.asarray(coil.centre)[None, :]
        + coil.radius * np.cos(theta)[:, None] * u[None, :]
        + coil.radius * np.sin(theta)[:, None] * v[None, :]
    )
    dl = np.diff(vertices, axis=0)
    midpoint = 0.5 * (vertices[:-1] + vertices[1:])
    return midpoint, dl


def loop_field(points: np.ndarray, coil: Coil, current: float = 1.0) -> np.ndarray:
    """Evaluate a discretised circular coil at one or more 3-D points."""
    points = np.atleast_2d(np.asarray(points, dtype=float))
    midpoint, dl = loop_segments(coil)
    displacement = points[:, None, :] - midpoint[None, :, :]
    distance = np.linalg.norm(displacement, axis=2)
    if np.any(distance < max(1e-12, coil.wire_radius * 0.1)):
        raise ValueError("Observation point lies on or too close to the conductor")
    cross = np.cross(dl[None, :, :], displacement)
    field = (MU0 / (4.0 * np.pi)) * np.sum(cross / distance[:, :, None] ** 3, axis=1)
    return field * current * coil.turns


def analytic_on_axis(z: np.ndarray, radius: float, current: float, turns: int = 1) -> np.ndarray:
    """Analytical axial field of a thin circular loop centred at z=0."""
    z = np.asarray(z, dtype=float)
    return MU0 * turns * current * radius**2 / (2.0 * (radius**2 + z**2) ** 1.5)


def influence_matrix(
    points: np.ndarray,
    coils: Sequence[Coil],
    *,
    component: int | None = None,
) -> np.ndarray:
    """Build the linear mapping from coil current to sampled magnetic field."""
    points = np.atleast_2d(np.asarray(points, dtype=float))
    fields = np.stack([loop_field(points, coil, 1.0) for coil in coils], axis=-1)
    if component is None:
        return fields.reshape(points.shape[0] * 3, len(coils))
    if component not in (0, 1, 2):
        raise ValueError("component must be 0, 1, 2, or None")
    return fields[:, component, :]


def superposed_field(points: np.ndarray, coils: Sequence[Coil], currents: np.ndarray) -> np.ndarray:
    """Evaluate the full vector field generated by a current vector."""
    currents = np.asarray(currents, dtype=float)
    if currents.shape != (len(coils),):
        raise ValueError("currents must have one value per coil")
    full = influence_matrix(points, coils)
    return (full @ currents).reshape(-1, 3)

